### ISSUE TITLE
No entity found for query

### ISSUE THREAD

**Issue by wd0472** [actframework/act-sql-common#13]
在使用JPADao.q().first()、JPADao.q().fetch()  如果数据没有查询到数据，建议返回null，不建议直接提示报错信息

**Comment by wd0472** [comment]
javax.persistence.NoResultException: No entity found for query
	at org.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:532)
	at act.db.jpa.JPAQuery.first(JPAQuery.java:141)
	at com.wykj.mcs.controllers.Application.test(Application.java:64)
	at com.wykj.mcs.controllers.ApplicationMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:815)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:480)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:48)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:517)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:203)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1050)
	at act.route.Router$ContextualHandler.handle(Router.java:1596)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:159)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wd0472** [comment]
javax.persistence.NoResultException: No entity found for query
	at org.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:532)
	at act.db.jpa.JPAQuery.first(JPAQuery.java:141)
	at com.wykj.mcs.controllers.Application.test(Application.java:64)
	at com.wykj.mcs.controllers.ApplicationMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:815)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:480)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:48)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:517)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:203)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1050)
	at act.route.Router$ContextualHandler.handle(Router.java:1596)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:159)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wd0472** [comment]
javax.persistence.NoResultException: No entity found for query
	at org.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:532)
	at act.db.jpa.JPAQuery.first(JPAQuery.java:141)
	at com.wykj.mcs.controllers.Application.test(Application.java:64)
	at com.wykj.mcs.controllers.ApplicationMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:815)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:480)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:48)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:517)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:203)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1050)
	at act.route.Router$ContextualHandler.handle(Router.java:1596)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:159)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by greenlaw110** [comment]
this issue is superseded with https://github.com/actframework/act-jpa-common/issues/6
