### ISSUE TITLE
Hot reload error caused by HikariCP

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-sql-common#21]
Error stack:

```
2019-03-27 07:03:10,272 ERROR a.a.App@[jobs-thread-3] - Block issue encountered
org.osgl.exception.ConfigurationException: Error init SQL db service
	at org.osgl.util.E.invalidConfiguration(E.java:300)
	at act.db.sql.SqlDbService.init(SqlDbService.java:149)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:76)
	at act.job.Job$4.apply(Job.java:449)
	at act.job.Job.doJob(Job.java:407)
	at act.job.Job.run(Job.java:338)
	at act.job.Job$LockableJobList$1.run(Job.java:108)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:529)
	at act.job.Job.doJob(Job.java:407)
	at act.job.Job.run(Job.java:338)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.1.v20171221-bd47e8f): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:846)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:216)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getServerSession(EntityManagerFactoryDelegate.java:251)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.getServerSession(EntityManagerFactoryImpl.java:283)
	at act.db.eclipselink.EclipseLinkService.createEntityManagerFactory(EclipseLinkService.java:93)
	at act.db.jpa.JPAService.createEntityManagerFactory(JPAService.java:282)
	at act.db.jpa.JPAService.dataSourceProvided(JPAService.java:74)
	at act.db.sql.SqlDbService.doInitDataSource(SqlDbService.java:271)
	at act.db.sql.SqlDbService.initDataSource(SqlDbService.java:253)
	at act.db.sql.SqlDbService.init(SqlDbService.java:118)
	... 16 common frames omitted
Caused by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:316)
	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:147)
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:170)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.setOrDetectDatasource(DatabaseSessionImpl.java:228)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:804)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:254)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:759)
	... 25 common frames omitted
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:135)
	... 30 common frames omitted
2019-03-27 07:03:10,279 WARN  a.j.Job@[jobs-thread-3] - error executing job 2k9b0d7f7l.Y
act.boot.app.BlockIssueSignal: null
```

**Comment by greenlaw110** [comment]
This issue is caused by https://github.com/actframework/act-eclipselink/issues/12
